// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DBSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LightType     string                 `protobuf:"bytes,2,opt,name=light_type,json=lightType,proto3" json:"light_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBSummary) Reset() {
	*x = DBSummary{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBSummary) ProtoMessage() {}

func (x *DBSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBSummary.ProtoReflect.Descriptor instead.
func (*DBSummary) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *DBSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DBSummary) GetLightType() string {
	if x != nil {
		return x.LightType
	}
	return ""
}

type ServiceSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Color         string                 `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceSummary) Reset() {
	*x = ServiceSummary{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceSummary) ProtoMessage() {}

func (x *ServiceSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceSummary.ProtoReflect.Descriptor instead.
func (*ServiceSummary) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceSummary) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *ServiceSummary) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type UserSummaryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Username        string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	UserSummaryName string                 `protobuf:"bytes,2,opt,name=user_summary_name,json=userSummaryName,proto3" json:"user_summary_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserSummaryRequest) Reset() {
	*x = UserSummaryRequest{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSummaryRequest) ProtoMessage() {}

func (x *UserSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSummaryRequest.ProtoReflect.Descriptor instead.
func (*UserSummaryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *UserSummaryRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserSummaryRequest) GetUserSummaryName() string {
	if x != nil {
		return x.UserSummaryName
	}
	return ""
}

type UserSummaryResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserSummaryName string                 `protobuf:"bytes,1,opt,name=user_summary_name,json=userSummaryName,proto3" json:"user_summary_name,omitempty"`
	DbSummary       *DBSummary             `protobuf:"bytes,2,opt,name=db_summary,json=dbSummary,proto3" json:"db_summary,omitempty"`
	ServiceSummmary *ServiceSummary        `protobuf:"bytes,3,opt,name=service_summmary,json=serviceSummmary,proto3" json:"service_summmary,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserSummaryResponse) Reset() {
	*x = UserSummaryResponse{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSummaryResponse) ProtoMessage() {}

func (x *UserSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSummaryResponse.ProtoReflect.Descriptor instead.
func (*UserSummaryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *UserSummaryResponse) GetUserSummaryName() string {
	if x != nil {
		return x.UserSummaryName
	}
	return ""
}

func (x *UserSummaryResponse) GetDbSummary() *DBSummary {
	if x != nil {
		return x.DbSummary
	}
	return nil
}

func (x *UserSummaryResponse) GetServiceSummmary() *ServiceSummary {
	if x != nil {
		return x.ServiceSummmary
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *HealthCheckRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type HealthCheckResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	HealthDb           string                 `protobuf:"bytes,1,opt,name=health_db,json=healthDb,proto3" json:"health_db,omitempty"`
	HealthOtherService string                 `protobuf:"bytes,2,opt,name=health_other_service,json=healthOtherService,proto3" json:"health_other_service,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheckResponse) GetHealthDb() string {
	if x != nil {
		return x.HealthDb
	}
	return ""
}

func (x *HealthCheckResponse) GetHealthOtherService() string {
	if x != nil {
		return x.HealthOtherService
	}
	return ""
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\agrpcapi\x1a\x1fgoogle/protobuf/timestamp.proto\":\n" +
	"\tDBSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"light_type\x18\x02 \x01(\tR\tlightType\"V\n" +
	"\x0eServiceSummary\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x14\n" +
	"\x05color\x18\x02 \x01(\tR\x05color\"\\\n" +
	"\x12UserSummaryRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12*\n" +
	"\x11user_summary_name\x18\x02 \x01(\tR\x0fuserSummaryName\"\xb8\x01\n" +
	"\x13UserSummaryResponse\x12*\n" +
	"\x11user_summary_name\x18\x01 \x01(\tR\x0fuserSummaryName\x121\n" +
	"\n" +
	"db_summary\x18\x02 \x01(\v2\x12.grpcapi.DBSummaryR\tdbSummary\x12B\n" +
	"\x10service_summmary\x18\x03 \x01(\v2\x17.grpcapi.ServiceSummaryR\x0fserviceSummmary\"0\n" +
	"\x12HealthCheckRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"d\n" +
	"\x13HealthCheckResponse\x12\x1b\n" +
	"\thealth_db\x18\x01 \x01(\tR\bhealthDb\x120\n" +
	"\x14health_other_service\x18\x02 \x01(\tR\x12healthOtherService2\xaa\x01\n" +
	"\x11AggregatorService\x12K\n" +
	"\x0eGetUserSummary\x12\x1b.grpcapi.UserSummaryRequest\x1a\x1c.grpcapi.UserSummaryResponse\x12H\n" +
	"\vHealthCheck\x12\x1b.grpcapi.HealthCheckRequest\x1a\x1c.grpcapi.HealthCheckResponseB@Z>github.com/Krunis/summary-aggregation/packages/grpcapi;grpcapib\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_goTypes = []any{
	(*DBSummary)(nil),             // 0: grpcapi.DBSummary
	(*ServiceSummary)(nil),        // 1: grpcapi.ServiceSummary
	(*UserSummaryRequest)(nil),    // 2: grpcapi.UserSummaryRequest
	(*UserSummaryResponse)(nil),   // 3: grpcapi.UserSummaryResponse
	(*HealthCheckRequest)(nil),    // 4: grpcapi.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 5: grpcapi.HealthCheckResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_api_proto_depIdxs = []int32{
	6, // 0: grpcapi.ServiceSummary.time:type_name -> google.protobuf.Timestamp
	0, // 1: grpcapi.UserSummaryResponse.db_summary:type_name -> grpcapi.DBSummary
	1, // 2: grpcapi.UserSummaryResponse.service_summmary:type_name -> grpcapi.ServiceSummary
	2, // 3: grpcapi.AggregatorService.GetUserSummary:input_type -> grpcapi.UserSummaryRequest
	4, // 4: grpcapi.AggregatorService.HealthCheck:input_type -> grpcapi.HealthCheckRequest
	3, // 5: grpcapi.AggregatorService.GetUserSummary:output_type -> grpcapi.UserSummaryResponse
	5, // 6: grpcapi.AggregatorService.HealthCheck:output_type -> grpcapi.HealthCheckResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
